const DEBUG='http://127.0.0.1:9223'
class CDP{constructor(ws){this.ws=ws;this.seq=0;this.p=new Map();this.log=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.p.has(m.id)){const{r,j}=this.p.get(m.id);this.p.delete(m.id);m.error?j(new Error(JSON.stringify(m.error))):r(m.result)}else if(m.method==='Network.requestWillBeSent'){if(m.params.request.url.includes('/api/'))this.log.push('REQ '+m.params.request.method+' '+m.params.request.url)}else if(m.method==='Network.responseReceived'){if(m.params.response.url.includes('/api/'))this.log.push('RES '+m.params.response.status+' '+m.params.response.url)}else if(m.method==='Network.loadingFailed'){this.log.push('FAIL '+m.params.errorText+' '+(m.params.requestId))}}}static async c(u){const ws=new WebSocket(u);await new Promise((a,b)=>{ws.onopen=a;ws.onerror=e=>b(new Error('ws'))});return new CDP(ws)}send(m,pr={}){const id=++this.seq;return new Promise((r,j)=>{this.p.set(id,{r,j});this.ws.send(JSON.stringify({id,method:m,params:pr}))})}async ev(x){const r=await this.send('Runtime.evaluate',{expression:x,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}close(){try{this.ws.close()}catch{}}}
const t=await fetch(`${DEBUG}/json/new?about:blank`,{method:'PUT'}).then(r=>r.json())
const c=await CDP.c(t.webSocketDebuggerUrl);await c.send('Page.enable');await c.send('Runtime.enable');await c.send('Network.enable')
await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false})
await c.send('Page.navigate',{url:'http://127.0.0.1:5174/videos'});await new Promise(r=>setTimeout(r,5000))
console.log(c.log.join('\n'))
console.log('skeleton=',await c.ev(`document.querySelectorAll('[class*="skeleton"]').length`))
c.close();process.exit(0)
